Add to ros2 documentation one or multiple tutorials to create a first simulation with Webots
cyberbotics/ros2_documentation pull request #1
Opened 2021-11-12 11:37 UTC by BenjaminHug8

**Context**
This PR aims to create a tutorial on the [official ros2 documentation page](https://docs.ros.org/en/rolling/Tutorials.html) most probably in the **Advanced** tab.

There is already our tutorials with `Turtlebot 3` in the **Demos** section, but this is not as visible as a tutorial.

This should give more information to a new user of Webots how to use ROS2 with the simulator.

**Tips**
To test the tutorial, follow the instructions at the top of this [page](https://docs.ros.org/en/rolling/Contributing/Contributing-To-ROS-2-Documentation.html).

2021-11-12 11:42 UTC, BenjaminHug8 commented
I am still correcting some misspelling but I would be glad if you can take a first look @omichel .

2021-11-12 13:29 UTC, omichel commented
I would rename the title to something more in line with other tutorials, like "Running a Robot Simulation (Webots)".

2021-11-12 15:09 UTC, omichel commented on source/Tutorials/Simulators/Creating-Your-First-ROS2-Webots-Simulation.rst
> +It provides a complete development environment to model, program and simulate robots.
Let's put it in context of the previous simulator used, e.g., turtlesim:
```suggestion
Webots is a robot simulator that can used with ROS 2.
Unlike turtlesim, it provides physics-based models for robots, sensors, actuators and objects.
This provides realistic simulation results that should match the behaviors observed in the real world.
Hence, what you get in simulation is very close to what you will observe when transferring your ROS 2 controllers to a real robot.
```

2021-11-12 15:09 UTC, omichel commented on source/Tutorials/Simulators/Creating-Your-First-ROS2-Webots-Simulation.rst
> +Webots_ros2 is a package offering an interface between ROS2 and Webots, using the sub-package named webots_ros2_driver that you will use in this tutorial.
```suggestion
webots_ros2 is a package offering an interface between ROS2 and Webots, using the sub-package named webots_ros2_driver that you will use in this tutorial.
```

2021-11-15 10:57 UTC, omichel requested changes

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +**Goal:** Install and discover the Webots simulator with the webots_ros2 package.
```suggestion
**Goal:** Setup a robot simulation and control it from ROS 2.
```

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +Creating a Robot Simulation (Webots)
I would change "Creating" to "Setting-up" or "Running" because we not creating the simulation world file in there.

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +There is also some other sub-packages containing examples with different robots such as the TurtleBot 3 you may find on the :doc:`../../Tutorials` page under the ``Demos`` section.
```suggestion
There are also some other sub-packages containing demos with different robots such as the TurtleBot 3.
Such demos are detailed in the :doc:`../../Tutorials` page under the ``Demos`` section.
```

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +This tutorial will introduce you how to create your first simulation by modeling your robot and implementing a Python plugin derived from webots_ros2_driver.
We not any more modeling the robot here.

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +This tutorial assume you followed the tutorials :doc:`../Creating-Your-First-ROS2-Package` and :doc:`../Launch-Files/Using-ROS2-Launch-For-Large-Projects`.
```suggestion
This tutorial assumes you followed the tutorials :doc:`../Creating-Your-First-ROS2-Package` and :doc:`../Launch-Files/Using-ROS2-Launch-For-Large-Projects`.
```

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +Precedent tutorials
```suggestion
Previous tutorials
```

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +In this tutorial, you created a simulation with Webots, modeled your own robot and implemented a Python plugin to use its motors and sensors.
We didn't modeled anything.

2021-11-15 10:57 UTC, omichel commented on source/Tutorials/Simulators/Creating-a-Robot-Simulation-Webots.rst
> +2 Create the simulation world in Webots
We don't really create the simulation here.
```suggestion
2 Setup the simulation world in Webots
```

2021-11-15 14:10 UTC, lukicdarkoo requested changes
It looks very good and clean. However, I would rather simplify the tutorial and allow a user to control the robot (with `cmd_vel`) as soon as possible with as least code as possible. Also, instead of the Webots robot, I would rather go with a TurtleBot to depict Webots' visual fidelity. What do you think?

2021-11-15 14:10 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +import math
This is very nice, but we can expose the same interface through the URDF configuration file with `webots_ros2_control`. Why did you choose to go with this approach?

2021-11-15 14:19 UTC, BenjaminHug8 commented
> It looks very good and clean. However, I would rather simplify the tutorial and allow a user to control the robot (with `cmd_vel`) as soon as possible with as least code as possible. Also, instead of the Webots robot, I would rather go with a TurtleBot to depict Webots' visual fidelity. What do you think?

The idea was to have a tutorial where the user starts from nothing and then create his own robot. With Olivier we thought that keeping the part where the user build his robot would not be accepted on the official ROS2 documentation, thus I put it on the Gihub of `webots_ros2`.
On one hand I think that using Turtlebot will be good looking and somewhat will link well with the 2 demos we have, on the other hand I also think users will benefit of a tutorial on how building their robot.

2021-11-15 14:26 UTC, omichel commented
Yes, one of the advantages of using a super simple robot in a world file is that it is simpler for the beginners: a single world file, no concept of proto, the devices of the robot are minimalist and can be easily found in the world file, which is super small comparing to a Turtlebot proto.

2021-11-15 14:35 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        sudo apt install ./webots_VERSION_amd64.deb
That is true. But in the case the user will build his robot or just want to open the world given to see what it looks like I think it will be great he can install it (before launching any `webots_ros2` related stuff)?

But a comment to indicate it can be automatically downloaded is good tho.

2021-11-15 14:41 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        sudo apt install ./webots_VERSION_amd64.deb
I tend to agree with @lukicdarkoo: if not needed, this will simplify the instructions and we don't expect the user will do anything else than what (s)he is instructed during the tutorial, so I believe installing Webots explicitly is superfluous here.

2021-11-15 14:42 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Please go on this `page <https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Create-Webots-Robot>`_ to learn how to create your own robot or download a premade one.
It is a good point to have something quickly runable for the user to test. Is the fact to go on our Github to download the file of the world the same that recommend them to import a premade robot ?

2021-11-15 14:50 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Please go on this `page <https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Create-Webots-Robot>`_ to learn how to create your own robot or download a premade one.
Instead of inviting the users to another tutorial here, we should point directly to the zip file to download, e.g., https://github.com/cyberbotics/webots_ros2/wiki/assets/tutorialCreateWebotsRobot/my_world.zip and refer to the tutorial afterwards as an option in case the user want to understand the details of this file.

2021-11-15 14:54 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/my_robot_driver_sensor.py
You mean keep the first `my_robot_driver.py` that is listening `/cmd_vel` and just create a node that listen to the sensors and publish commands on `/cmd_vel`?

Don't you think that it would add a little bit more complexity as there is more files and more nodes to launch? (Thus an extra node is more clean if we want to keep the behavior of the first `my_robot_driver.py` , I admit).

2021-11-15 14:57 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +import math
The idea was to not use `webots_ros2_control` as it depends on `ros2_control` and we wanted to keep it with the minimum amount of packages (only 4 packages here).

2021-11-15 14:58 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        sudo apt install ./webots_VERSION_amd64.deb
Ok I will change that.

2021-11-15 16:32 UTC, omichel commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +import math
Yes, that could be the next tutorial indeed...

2021-11-15 16:32 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +import math
It does not cost much to write a note, I ll do it then!

2021-11-15 16:35 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/my_robot_driver_sensor.py
> You mean keep the first my_robot_driver.py that is listening /cmd_vel and just create a node that listen to the sensors and publish commands on /cmd_vel?

Exactly.

> Don't you think that it would add a little bit more complexity as there is more files and more nodes to launch? (Thus an extra node is more clean if we want to keep the behavior of the first my_robot_driver.py , I admit).

There is the same number of files and you have only one extra node to launch. Although it is slightly simpler to use Webots ROS 2 plugins it is generally a bad practice. The obstacle avoidance controller should work with a real robot as well.

2021-11-15 16:40 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/my_robot_driver_sensor.py
I will change that.

2021-11-16 14:00 UTC, BenjaminHug8 commented
I handled the comments of @lukicdarkoo in the last commit.

I will wait the comments of Joachim.

2021-11-16 16:35 UTC, joachimhgg reviewed
Feel free to take in account or not the suggestions, some of them are obvious or subjective. Usually for the ROS tutorials, does it has to be code and then explication or code following explication? In any case I think it would be better to keep the same order.
I found it makes the tutorial heavier the fact to duplicate some part of the code to explain them.
Otherwise, the tutorial is really clear and easy to follow, I did not had any issue to do or understand it..

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Add a file ``obstacle_avoider.py`` to ``my_package/my_package/`` and fill it with:
consistency (in .. create a file... )

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +This node will simply create a publisher for the command and subscribe to the sensors topics here:
```suggestion
This node will create a publisher for the command and subscribe to the sensors topics here:
```

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Otherwise if only the left sensor detects an obstacle the command will make the robot turn right.
```suggestion
Otherwise, if only the left sensor detects an obstacle the command will make the robot turn anticlockwise.
```

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +And finally when a measure is recieved from the right sensor a command will be sent to the topic ``/cmd_vel`` in case any of the two sensors has detect an obstacle.
```suggestion
Finally, a command will be sent to the topic ``/cmd_vel`` when a measure is received from a sensor, i.e. when one of the two sensors has detected an obstacle.
```

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +You will also have to slightly modify these two other files in order to launch your new node.
```suggestion
You have to modify these two other files to launch your new node.
```

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +And finally in your file ``robot_launch.py`` replace ``def generate_launch_description():`` by the code bellow:
consistency

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +This will create an ``obstacle_avoider`` node and it will be prepared to be launched in ``LaunchDescription``.
```suggestion
This will create an ``obstacle_avoider`` node. It will be prepared to be launched in ``LaunchDescription``.
```
Sentence a bit long, not clear but don't know how to do better.

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Go to your file ``setup.py`` and add ``'obstacle_avoider = my_package.obstacle_avoider:main'`` to ``'console_scripts'``:
consistency

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +9 Going further
The `going further` part actually includes all the following

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +From a terminal in your ROS2 working directory run:
```suggestion
From a terminal in your ROS2 workspace run:
```

2021-11-16 16:35 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +First your robot will go forward and before hitting the wall it will turn clockwise.
```suggestion
Your robot will go forward and before hitting the wall it will turn clockwise.
```

2021-11-17 10:06 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/setup.py
I agree for the `Here`.

Otherwise concerning code and explications it seems to not be hard constraint. [Here](https://docs.ros.org/en/rolling/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.html#examine-the-code) is an example.

But generally the explanations come before the code so I will adapt this.

2021-11-17 11:21 UTC, BenjaminHug8 commented
> I found it makes the tutorial heavier the fact to duplicate some part of the code to explain them.

If you check the other ROS tutorials, you will see that usually when there is a file they will first show it entirely and then repeat the code block by block to explain it.
But it is true that if I can remove some repetition it will be lighter to read.

2021-11-17 15:59 UTC, BenjaminHug8 commented
I integrated the review of @joachimhgg in the 2 last commits.

Let me know if you have any comments or suggestions about this tutorial (and the one on [webots_ros2](https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Create-Webots-Robot#build-the-robot).

2021-11-17 16:20 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +A custom robot is already modeled in this world ``my_world.wbt``.
```suggestion
This is actually a fairly simple text file you can visualize in a text editor.
A simple robot is already included in this ``my_world.wbt`` world file.
```

2021-11-17 16:22 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +In the ``<package format="3">`` balise add the following:
```suggestion
Add the following inside the ``<package format="3">`` tag:
```

2021-11-17 16:27 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Go to your file ``package.xml`` and in the ``<package format="3">`` balise add the following:
```suggestion
Go to your file ``package.xml`` and in the ``<package format="3">`` tag add the following:
```

2021-11-17 16:32 UTC, omichel requested changes

2021-11-17 16:32 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +10 Creating a ROS node to avoid obstacle
```suggestion
10 Creating a ROS node to avoid obstacles
```

2021-11-19 14:49 UTC, BenjaminHug8 commented
I added the file `Tutorial-Create-Webots-Robot.md`. This file is the tutorial on the `webots_ros2` on how to construct a robot in webots.

In order to make reviews on it I put a copy in this PR.

2021-11-19 15:49 UTC, joachimhgg reviewed
About the tutorial to create a robot on `webots_ros2`:

It is an easy tutorial but redundant and long to do since you have to do all your robot by hand. Nevertheless, I think it is usefull when you 're starting with Webots and it is well explained. I compared the file that I have done thanks to the tutorial with the given world and it is not the same. I sent it to you. 

Maybe we can explain more how to run rosrun at the end? don't know if it is the purpose of the tutorial

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Add to your robot a `Physics` node to the corresponding field in order to enable the collision with other objects.
```suggestion
Add to your robot a `Physics` node to the field `physics` in order to enable the collision with other objects.
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Then select `jointParameters` and add a `HingeJointParameters` node.
```suggestion
Then, select `jointParameters` and add a `HingeJointParameters` node.
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Select `device`, add a `RotationalMotor` node and then configure the `HingeJointParameters` and `RotationalMotor` nodes like below.
```suggestion
Select `device`, add a `RotationalMotor` node and configure the `HingeJointParameters` and `RotationalMotor` nodes like below.
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +`axis` will indicate around which axis the wheel should rotate and `anchor` indicates an offset.
```suggestion
`axis` will indicate around which axis the wheel should rotate and `anchor` indicates an offset.
```
which offset?

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Next select `endPoint`, add a `Solid` node and set it up like here in a similar manner you did for the body of the robot:
```suggestion
Select `endPoint`, add a `Solid` node and set it up like here in a similar manner you did for the body of the robot:
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Then change the name to `left wheel` and add to the `boundingObject` a `WHEEL` node (you will find it again in the `USE` field).
```suggestion
Change the name to `left wheel` and add to the `boundingObject` a `WHEEL` node (you will find it again in the `USE` field).
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Add to your robot a `Physics` node to its corresponding field once again in order to enable the collisions.
```suggestion
Add to your `endPoint Solid` a `Physics` node to its field `physics` once again to enable the collisions.
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Creating the second wheel is bit easier as you can use the `DEF-USE` mechanism of Webots.
```suggestion
Creating the second wheel is easier as you can use the `DEF-USE` mechanism of Webots.
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Select `Robot` > `children` > `HingeJoint` and then add a `HingeJoint` node.
```suggestion
Select `Robot` > `children` > `HingeJoint` and add a `HingeJoint` node.
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Then configure the sensor as described in the following image in order to correctly place and model the sensor:
```suggestion
Then, configure the sensor as described in the following image in order to correctly place and model the sensor:
```

2021-11-19 15:49 UTC, joachimhgg commented on source/Tutorials/Simulators/Tutorial-Create-Webots-Robot.md
> +Creating the second sensor is straightforward and you can follow this structure:
```suggestion
Creating the second sensor is straightforward and you can copy/paste the `ds0 DistanceSensor `node and follow this structure:
```

2021-11-22 10:54 UTC, BenjaminHug8 commented
> Maybe we can explain more how to run rosrun at the end? don't know if it is the purpose of the tutorial

For me we can expect users to know some basis of ROS for this tutorial.

2021-11-22 10:57 UTC, omichel commented
> For me we can expect users to know some basis of ROS for this tutorial.

Yes, if some knowledge from other basic ROS tutorials is needed, we should mention them in the prerequisites section.

2021-11-22 11:00 UTC, BenjaminHug8 commented
> I compared the file that I have done thanks to the tutorial with the given world and it is not the same.

One mistake was due to a wrong image in the tutorial, otherwise it is quite correct. I think it will be normal for users to make mistakes and to compare the given world with their.

2021-11-22 13:05 UTC, BenjaminHug8 commented
@omichel may I ask you to test the 2 tutorials?

In case you want to make a review on the tutorial `Create Webots Robot` which is on [webots_ros2](https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Create-Webots-Robot), there is a copy of the .md file in this PR.

2021-11-22 15:27 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Code/obstacle_avoider.py
> +        self.create_subscription(Range, 'r_sensor', self.__r_sensor_callback, 1)
```suggestion
        self.create_subscription(Range, 'left_sensor', self.__left_sensor_callback, 1)
        self.create_subscription(Range, 'right_sensor', self.__right_sensor_callback, 1)
```

2021-11-22 15:27 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Code/obstacle_avoider.py
> +        self.__r_sensor_value = msg.range
```suggestion
    def __left_sensor_callback(self, message):
        self.__left_sensor_value = message.range

    def __right_sensor_callback(self, message):
        self.__right_sensor_value = message.range
```

2021-11-23 09:56 UTC, omichel commented
I believe we need to handle the Linux / Windows / macOS cases for command lines instructions like installing the webots_ros2 package, creating directories, etc., like it is done in other tutorials, for example https://docs.ros.org/en/foxy/Tutorials/Topics/Topic-Statistics-Tutorial.html

2021-11-23 14:05 UTC, lukicdarkoo commented
> I believe we need to handle the Linux / Windows / macOS cases for command lines instructions like installing the webots_ros2 package, creating directories, etc., like it is done in other tutorials, for example https://docs.ros.org/en/galactic/Tutorials/FastDDS-Configuration/FastDDS-Configuration.html and https://docs.ros.org/en/foxy/Tutorials/Topics/Topic-Statistics-Tutorial.html

For Windows, we need to handle this first:
https://github.com/cyberbotics/webots_ros2/issues/303#issuecomment-976574206

Regarding macOS, I don't think it is relevant anymore as the support has been downgraded to Tier 3.

2021-11-23 15:43 UTC, omichel commented
I made many small modifications, fixed English, fixed details, added references, provided better explanations, etc.
The first part (until the robot moves forwards) is now pretty satisfactory to me.
However, the second parts involving the sensors seems weird: (1) it doesn't work and (2) it seems we are sending contradictory twist messages at the same time (which could explain why it doesn't work). I believe we should provide a cleaner example.

2021-11-23 16:09 UTC, BenjaminHug8 commented
> However, the second parts involving the sensors seems weird

I will check if I can simplify some parts.

> (1) it doesn't work

A change in the name of the variables broke a part, it works on my side now.

> (2) it seems we are sending contradictory twist messages at the same time

This part is also solved.
I pushed a commit for 1) and 2).

2021-11-23 17:03 UTC, omichel commented
OK, it looks good to me now.
I changed it quite a bit since I started the review.
So I believe it would be nice if @lukicdarkoo and @joachimhgg could go through it carefully once again to be sure it looks all good also for you.
The goal is really to show the most simple system exhibiting a control algorithm.

2021-11-23 17:05 UTC, omichel submitted a review, later dismissed

2021-11-23 17:10 UTC, omichel commented
And yes, we should also modify the instructions to support Windows as well as described by @lukicdarkoo.
@BenjaminHug8: can you take care of this?
We will wait for the Windows instructions before testing again.

2021-11-24 07:43 UTC, BenjaminHug8 commented
> @BenjaminHug8: can you take care of this?

Of course, I am already working on it.

2021-11-24 08:07 UTC, omichel commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +                command_right = MAX_SPEED * clamp(1 - ratio_turn, 0, 1)
That seems wrong. The conversion from the twist message (desired linear and angular velocities) to motor speeds for a differential wheels robot is not correct. We should correct it and explain it a little bit in the text.

2021-11-24 10:17 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +                command_right = MAX_SPEED * clamp(1 - ratio_turn, 0, 1)
Should be resolved with the `update conversion speed` commit.

2021-11-24 10:28 UTC, omichel commented on source/Tutorials/Simulators/Code/my_robot_driver.py
> +                command_right = MAX_SPEED * clamp(1 - ratio_turn, 0, 1)
Thank you.
However, I believe it is better to use "counterclockwise" (American English) rather than anti-clockwise (British English).
Also, I wouldn't change the fact that the robot goes forward and bump into the wall. Because it is nice to see the problem and then come with a solution (use the sensors to avoid the obstacles).

2021-11-24 10:48 UTC, omichel requested changes

2021-11-24 10:48 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        cd \ros2_ws
In most of the other tutorials, this folder is named `dev_ws` instead. Only a few tutorials seems to use `ros2_ws` (after introducing it explicitly). I believe it is better to remain consistent with the majority of the tutorials:
```suggestion
        cd \dev_ws
```

2021-11-24 10:48 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        cd ~/ros2_ws/src
```suggestion
        cd ~/dev_ws/src
```

2021-11-24 10:48 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        cd \ros2_ws\src
```suggestion
        cd \dev_ws\src
```

2021-11-24 11:13 UTC, BenjaminHug8 commented
Shall we ask @lukicdarkoo and @joachimhgg to check again the tutorial now @omichel?

2021-11-24 11:20 UTC, omichel commented
Lets finalize the clean-up before.

2021-11-24 11:32 UTC, BenjaminHug8 commented
I removed unused images, the file .md containing the tutorial on `webots_ros2` to create a custom robot and I also changed some names in the duplicated files for the part 2 with sensors (e.g. `"My robot Webots"` into `"My robot"`).

2021-11-24 11:47 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. image:: Image/Robot_clock_wise.png
```suggestion
.. image:: Image/Robot_clockwise.png
```
And we have to rename the file as well.

2021-11-24 11:49 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. image:: Image/Robot_clock_wise.png
Sorry, it would be better with a verb to be consistent with other file names.
```suggestion
.. image:: Image/Robot_turning_clockwise.png
```

2021-11-24 11:51 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. image:: Image/Robot_clock_wise.png
Done.

2021-11-24 11:54 UTC, omichel commented
Thank you. I believe we can ask now to @lukicdarkoo and @joachimhgg to test it again carefully and report any problem they may spot. It would be nice if one of you could test it on Windows.

2021-11-24 13:34 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        mkdir launch worlds
This doesn't work on Windows.

2021-11-24 14:43 UTC, lukicdarkoo requested changes
A few more suggestions to make it simpler

2021-11-24 14:43 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +
Here we need an explanation of why we want to change the file. We should mention:
- that `webots_ros2_driver` automatically creates a ROS 2 interface for most sensors
- that one can extend the interface using C++ or Python plugins
- that the differential drive Webots/ROS plugin doesn't exist as it is a part of the `ros2_control` package, but we are creating this file for demonstration purposes

2021-11-24 14:43 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +This node, named ``driver``, is located in the ``webots_ros2_driver`` package.
Maybe, we should also explain to users that the `driver` node uses a custom protocol based on IPC and shared memory to communicate with a robot in the simulation. A little technical details might be interesting to users

2021-11-24 14:43 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Finally, the two nodes are started in such a way that if the ``webots`` launcher node is shutdown, the other ``my_robot_driver`` node will be shutdown as well.
This sentence is a bit confusing. I would use one sentence to explain:
```
        webots,
        my_robot_driver,
```
and another one to explain:
```
launch.actions.RegisterEventHandler(
            event_handler=launch.event_handlers.OnProcessExit(
                target_action=webots,
                on_exit=[launch.actions.EmitEvent(event=launch.events.Shutdown())],
            )
        )
```
The second part is optional and it shutdowns all nodes once the Webots process dies.

2021-11-24 14:43 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Finally before you can start the launch file, you have to modify the setup.py file to include the extra files you added.
```suggestion
Finally, before you can start the launch file, you have to modify the `setup.py` file to include the extra files you added.
```

2021-11-24 14:43 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/package_sensor.xml
```suggestion
.. literalinclude:: Code/package_sensor.xml
```
Maybe we can avoid explaining this line as well because it is a dependency of webots_ros2_driver

2021-11-24 14:46 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        mkdir launch worlds
No problem on my side with `mkdir` in Visual Studio Command Prompt.

2021-11-24 16:32 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/package_sensor.xml
Do you suggest to put it in the creation of the package?

In my opinion the user might not understand why there is this package when he is in the 1st part of the tutorial (without the sensors).
Currently the tutorial will use directly anything that has been setup, so the user can make links between the different files.

2021-11-29 10:50 UTC, BenjaminHug8 commented
I changed the installation part to get only `webots_ros2_driver` but I kept the background on `webots_ros2` and added a note to install `webots_ros2`.

I think it is great for users to have this but it might be too "commercial" for ROS2 committee.

Let me know what you think about it.

2021-11-29 10:58 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/package_sensor.xml
We just not include it in the tutorial. `sensor_msgs` comes with `ros-base`, so it should without explicitly specifying it

2021-11-29 11:19 UTC, omichel commented
I committed a little polishing of the latest contributions which look good to me.

2021-11-29 12:13 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/package_sensor.xml
It is even a part of `ros-core`:
```
$ apt-rdepends ros-galactic-ros-core | grep sensor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
  Depends: ros-galactic-sensor-msgs
ros-galactic-sensor-msgs
  Depends: ros-galactic-sensor-msgs
```

Don't get me wrong, if a package is going into production I would explicitly put `sensor_msgs` as a dependency. However, if we want to make the tutorial a little bit simpler then there is no strong need to mention it.

2021-11-29 12:39 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +.. literalinclude:: Code/package_sensor.xml
Ok I will remove it then, thank you!

2021-11-29 15:48 UTC, joachimhgg reviewed
Issue with the last part. Also do not forget to update the world.wbt with 2022a when available.

2021-11-29 15:48 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +    If you want to install the whole ``webots_ros2`` package, follow these `instructions <https://github.com/cyberbotics/webots_ros2/wiki/Getting-Started`_.
broken markdown, also it is pointing to the same tutorial

2021-11-29 15:48 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Open ``my_package/my_robot_driver.py`` in your favorite editor and replace its contents with the following:
```suggestion
Open ``src/my_package/my_package/my_robot_driver.py`` in your favorite editor and replace its contents with the following:
```
to avoid confusion with my_package folders

2021-11-29 15:48 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +Repeat the same commands as in tasks ``8`` to test your code.
```suggestion
Repeat the same commands as in tasks ``7`` to test your code.
```

2021-11-29 15:48 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        ros2 launch my_package robot_launch.py
do not work for me when I follow the step 7 again. The controller does not start. Also when I launch the command ros2 launch I get: 

```
WARNING: Target Webots version `R2021b` is not found, fallback to `R2021b revision 1`
[INFO] [webots-1]: process started with pid [201634]
[INFO] [driver-2]: process started with pid [201636]
[driver-2] Cannot open file: /tmp/webots-201634-vLpU51/WEBOTS_SERVER (retry count 1)
[driver-2] Cannot open file: /tmp/webots-201634-vLpU51/WEBOTS_SERVER (retry count 2)
```

2021-11-29 15:55 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +In particular, :doc:`../Turtlesim/Introducing-Turtlesim`, :doc:`../Topics/Understanding-ROS2-Topics`, :doc:`../Workspace/Creating-A-Workspace`, :doc:`../Creating-Your-First-ROS2-Package` and :doc:`..
No, but they give a flavor on how to work with a super simple, non-realistic, simulator. So, this might be helpful, although not strictly necessary.

2021-11-29 15:56 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        sudo apt-get install ros-{DISTRO}-webots-ros2-driver
In that case, I would rather remove the `-get` suffix in both cases because it is the old legacy version.

2021-11-30 07:26 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
>  From a terminal in your ROS 2 workspace run:
```suggestion
As in task ``7`` to launch the simulation, from a terminal in your ROS 2 workspace run:
```
to not make the impression that we have to repeat the commands of task 7 before moving to the next task.

2021-11-30 07:32 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        ros2 launch my_package robot_launch.py
As discussed together, it seems you miss a part of the tutorial.
Was it easy to miss that part or unclear?

2021-11-30 07:33 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
>  From a terminal in your ROS 2 workspace run:
(I just edited your proposal to make it a little bit simpler)

2021-11-30 07:38 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
>  From a terminal in your ROS 2 workspace run:
it could be nice to change the background of the code sections when they are related to explication

2021-11-30 09:33 UTC, BenjaminHug8 commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
>  From a terminal in your ROS 2 workspace run:
It seems not so easy to do it. I do not find a way to change only specific `literalinclude`.
I tried to play with `:emphasize-lines:` but the background is also yellow so we can not see any change.

Furthermore it will be quite different from all the other tutorials as none of them is changing the default background color.
@omichel do you think I should spend more time on this?

2021-11-30 09:36 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
>  From a terminal in your ROS 2 workspace run:
> @omichel do you think I should spend more time on this?

No.

2021-11-30 12:13 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +:download:`Download this world file <Code/my_world.wbt>` and move it inside ``my_package/worlds/``.
I am not sure whether it is a good idea, but we can provide a curl command for it. I saw they used it in the main ROS tutorial for Windows, so ROS assumes there is the curl command. However, the curl command throws an HTTPS-related error when called from the VS 2019 command prompt.

2021-11-30 14:20 UTC, omichel commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +:download:`Download this world file <Code/my_world.wbt>` and move it inside ``my_package/worlds/``.
I would avoid it if it throws errors in the console... And it seems the VS 2019 command prompt is often used with ROS 2, isn't it?

2021-11-30 14:45 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +            source install/setup.bash
```suggestion
```
This is not needed as we don't use any custom messages

2021-11-30 14:45 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +            ros2 topic pub /cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.1, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}'
```suggestion
            ros2 topic pub /cmd_vel geometry_msgs/Twist  "linear: { x: -0.1 }"
```
Single quotes don't work with Windows, also, it can be simplified

2021-11-30 14:48 UTC, lukicdarkoo commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +:download:`Download this world file <Code/my_world.wbt>` and move it inside ``my_package/worlds/``.
That's true, it is always used for compilation, so for this tutorial as well. I agree, it would be nice, but since we cannot find a clean solution it is better to avoid it.

2021-12-01 08:00 UTC, omichel commented
@joachimhgg and @lukicdarkoo: please approve this PR if you believe it is fine for you.

2021-12-01 08:01 UTC, omichel approved these changes

2021-12-01 08:23 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +            ros2 topic pub /cmd_vel geometry_msgs/Twist  "linear: { x: -0.1 }"
```suggestion
            ros2 topic pub /cmd_vel geometry_msgs/Twist  "linear: { x: 0.1 }"
```
To go forward

2021-12-01 08:23 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +In ``my_robot.urdf`` add the following content inside the ``<webots>`` tag:
It was not working for me because I replaced the content inside the `webots` tag and so remove the `plugin`. Through the tutorial, we only have to replace code or create new file. To avoid the confusion, I suggest either to specify that we need to keep plugin or add the plugin into the proposed code and change `add` by `replace`.

2021-12-01 08:23 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +
```suggestion
```

2021-12-01 08:23 UTC, joachimhgg commented on source/Tutorials/Simulators/Setting-up-a-Robot-Simulation-Webots.rst
> +        ros2 launch my_package robot_launch.py
I wrote it in the last review

2021-12-01 08:53 UTC, BenjaminHug8 commented
I think the tutorial is ready now.

2021-12-01 08:57 UTC, omichel approved these changes

2021-12-01 08:58 UTC, joachimhgg approved these changes

2021-12-01 09:10 UTC, merged