Migrate custom plugin tutorials to official documentation
cyberbotics/ros2_documentation pull request #10
Opened 2023-04-18 15:09 UTC by ygoumaz

Improve `Setting-Up-Simulation-Webots.rst` tutorial to embed all the information of the wiki tutorials about custom plugins.

2023-04-21 13:56 UTC, omichel requested changes

2023-04-21 13:56 UTC, omichel commented on source/Tutorials/Advanced/Simulation/Webots/Setting-Up-Simulation-Webots.rst
> +        - The ``properties`` argument is a dictionary created from the XML tags given in the URDF files (:ref:`4 Create the my_robot.urdf file`) and allows to pass parameters to the controller.
```suggestion
        - The ``properties`` argument is a dictionary created from the XML tags given in the URDF files (:ref:`4 Create the my_robot.urdf file`) and allows you to pass parameters to the controller.
```

2023-04-21 13:56 UTC, omichel commented on source/Tutorials/Advanced/Simulation/Webots/Setting-Up-Simulation-Webots.rst
> +        * The ``parameters`` argument is an unordered map of strings, created from the XML tags given in the URDF files (:ref:`4 Create the my_robot.urdf file`) and allows to pass parameters to the c
```suggestion
        * The ``parameters`` argument is an unordered map of strings, created from the XML tags given in the URDF files (:ref:`4 Create the my_robot.urdf file`) and allows to pass parameters to the controller. It is not used in this example.
```

2023-04-21 13:56 UTC, omichel commented on source/Tutorials/Advanced/Simulation/Webots/Setting-Up-Simulation-Webots.rst
>      However, URDF files usually contain much more information as explained in the :doc:`../../../Intermediate/URDF/URDF-Main`.
```suggestion
    However, URDF files usually contain much more information as explained in the :doc:`../../../Intermediate/URDF/URDF-Main` tutorial.
```

2023-04-21 13:56 UTC, omichel commented on source/Tutorials/Advanced/Simulation/Webots/Setting-Up-Simulation-Webots.rst
>  The ``robot_description`` parameter holds the contents of the URDF file which refers to the ``my_robot_driver.py`` Python plugin.
It could be a C++ plugin as well, e.g., `MyRobotDriver.cpp` C++ plugin.

2023-04-21 13:56 UTC, omichel commented on source/Tutorials/Advanced/Simulation/Webots/Code/my_robot_python.urdf
Can't we make it more consistent with the C++ version? E.g., remove the `my_package.`? Or add it in the C++ version? Or explain why we have such a difference.

2023-04-21 13:56 UTC, omichel commented on source/Tutorials/Advanced/Simulation/Webots/Setting-Up-Simulation-Webots.rst
At the end of the tutorial (Summary section) we refer to a Python plugin (we should change it to "Python or C++").

2023-04-21 15:43 UTC, ygoumaz commented on source/Tutorials/Advanced/Simulation/Webots/Code/my_robot_python.urdf
I checked and in C++ we depend on Pluginlib to load the plugin which requires the `namespace::Class` format, while for Python plugins `webots_ros2_driver` contains a `PythonPlugin` class which is loading of these types of plugins. The Python interpreter waits for the absolute folder path to the module to load it (`package_name.filename.Class`). I will add an explanation to make it clearer to the user.

2023-04-24 09:37 UTC, omichel approved these changes
Thank you.
It looks all good to me.

2023-04-24 09:39 UTC, merged