Update Windows compatibility to WSL in tutorials
cyberbotics/ros2_documentation pull request #2
Opened 2022-10-12 14:29 UTC by ygoumaz

ditto.

2022-10-13 16:19 UTC, omichel requested changes

2022-10-13 16:19 UTC, omichel commented on source/Tutorials/Advanced/Simulators/Webots.rst
> +On Windows, the communication between Webots and the controllers, running in WSL, is possibly via TCP connection.
```suggestion
On Windows, the communication between Webots (running in Windows) and the controllers (running in WSL) goes through a TCP connection.
```

2022-10-13 16:19 UTC, omichel commented on source/Tutorials/Advanced/Simulators/Webots.rst
> +        # On Windows, execute these in the WSL environment
I find this sentence (repeated several times) is a bit confusing as it seems we should execute these lines this ONLY on Windows, not on Linux. I would remove these sentences and add a sentence earlier that explain that all the Ubuntu and ROS commands should be entered in WSL for Windows users.

2022-10-14 07:02 UTC, omichel requested changes

2022-10-14 07:02 UTC, omichel commented on source/Tutorials/Advanced/Simulators/Webots.rst
> +On Windows, a WSL environment must be configured and used to run all the console and ROS commands contained in this tutorial.
```suggestion
On Windows, a WSL (Windows Subsystem for Linux) environment must be configured and used to run all the Linux and ROS commands contained in this tutorial. 
```

2022-10-14 07:18 UTC, omichel approved these changes
Thank you.

2022-10-14 07:56 UTC, ygoumaz commented
I convert this PR back to draft, as we should only merge it once Webots R2023a is released.

2022-10-28 15:04 UTC, ygoumaz commented
Finally, we decided to release the WSL changes earlier in `webots_ros2 2022.1.1-2`. This PR can be merged.

2022-10-28 15:05 UTC, merged